SET DELIMITER $$
CREATE TRIGGER check_seat AFTER INSERT ON PlaysTable
FOR EACH ROW
BEGIN
	IF NEW.Seat NOT BETWEEN 1 AND 4 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Seat not in range 1-4';
	END IF;
END$$
SET DELIMITER ;